import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:get/get.dart';

class MyLocal implements Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        "ar": {
          "check": "اضغط للتاكد من حجز الكورس ",
          "1": "مرحبا",
          "2": "تسجيل الدخول إلى حسابك",
          "3": "أدخل بريدك الإلكتروني",
          "4": "ادخل رقمك السري",
          "5": "تسجيل الدخول",
          "I Paid and want to activate the course":
              "تم الدفع واريد تفعيل الكورس",
          "don't press the button until you send total to vodafone cash number":
              "لا تضغط قبل ارسال الاجمالي عبر فودافون كاش",
          "6": "أنشئ حسابك",
          "7": "أدخل أسمك",
          "8": "انشاء الحساب",
          "9": "   طلاب \ كلية تجارة المنصورة ",
          "10": "اختار الفرقـة",
          "11": "         البحث عن الفصول والدورات... ",
          "12": "الفرقة الاولي",
          "13": "الفرقة الثانية",
          "14": "الفرقة الثالثـة",
          "15": "الفرقة الرابعـة",
          "16": "الكورسـات المقتـرحة",
          "17": "الأكثر مبيعًا",
          "18": " تجــارة عربـي  ",
          "19": " تجــارة انجليزي  ",
          "20": "مواد الفرقــة",
          "21": " اختار الدكتور",
          "22": "محتويات الدورة",
          "23": "اللغة",
          "24": "مشاركة التطبيق",
          "25": "تسجيل خروج",
          "26": "الصفحة الرئيسية",
          "27": "المفضلة",
          "28": "دوراتي",
          "29": "البروفايل",
          "30": "اختـار اللغة",
          "31": "العـربية",
          "32": "الانجليـزيـة",
          "33": "فـارغة",
          "34": "تصفح الكورسات",
          "35": " ليس لديك حساب؟",
          "36": "انشاء حساب",
          "37": "الاجمالي",
          "38": "تفعيـل الكـورس",
          "39": "لا تضغط على التفعيل حتى ترسل المجموع إلى رقم فودافون كاش",
          "40": "رقم فودافون كاش الخاص بنا",
          "41": "ارسل الاجمالي لرقم فودافون كاش",
          "42": "ادفع باستخدام فودافون كاش",
          "43": "رقم المحفظة",
          "44": "أرسل الاجمالي لتفعيل الدورة",
          "45": "التالي",
          "46": "تحقق مما إذا كانت هذه الدورة متاحة لك أم لا",
          "47": "اشترك",
        },
        "en": {
          "1": "Hello",
          "2": "Sign in to your account",
          "3": "Enter your Email",
          "4": "Enter your password",
          "5": "Sign in",
          "6": "Create your account",
          "7": "Enter your Name",
          "8": "Create account",
          "9": "Students Of Commerce\ El Mansoura",
          "10": "Choose Your Level",
          "11": "Search for classes, courses...",
          "12": "Level One",
          "13": "Level Two",
          "14": "Level Three",
          "15": "Level Four",
          "16": "Suggestions",
          "17": "Most Selling ",
          "18": "Arabic Commerce",
          "19": "English Commerce",
          "20": "Level Courses",
          "21": "Doctors Course",
          "22": "Course contents",
          "23": "Languages",
          "24": "Share App",
          "25": "Log out",
          "26": "Home",
          "27": "Favourite",
          "28": "my courses",
          "29": "Profile",
          "30": "Choose Language",
          "31": "Arabic",
          "32": "English",
          "33": "Empty",
          "34": "Explore Course",
          "35": "Dont\'t have an account? ",
          "36": "Sign up",
          "37": " Total ",
          "38": "activate course",
          "39":
              "don't press the button until you send total to vodafone cash number",
          "40": "Our Vodafone Cash Number",
          "41": "Send the total number to Vodafone Cash",
          "42": "Pay With vodafone cash",
          "43": "Wallet number",
          "44": "Send total to activate the course",
          "45": "Next",
          "46": "Check if this course available for you or not",
          "47": "Pay",
        },
      };
}
